---
protocol: 0.8.1
slug: add-numbers
name: Add Numbers
version: 0.1.0
input:
  variable:
    a:
      name: A
      view: number
      path: numbers.json
      key: a
    b:
      name: B
      view: number
      path: numbers.json
      key: b
  template:
    basic:
      name: Basic
      path: templates/input/basic.md
output:
  variable:
    c:
      name: C
      view: number
      path: sum.json
      key: c
  template:
    summary:
      name: Summary
      path: templates/output/summary.md
environment: 
  image: docker.io/library/python:slim-buster
  processor: cpu
  memory: tiny
script:
  uri: git@github.com:crosscompute/crosscompute-examples
  folder: add-numbers
  command: bash run.sh
example:
  - examples/integers
  - examples/floats
