---
protocol: 0.8.2
name: Add Numbers
version:
  name: 0.1.0
input:
  variables:
    - id: a
      name: A
      view: number
      path: numbers.json
      key: a
    - id: b
      name: B
      view: number
      path: numbers.json
      key: b
  templates:
    - id: basic
      name: Basic
      path: templates/input/basic.md
output:
  variables:
    - id: c
      name: C
      view: number
      path: sum.json
      key: c
  templates:
    - id: summary
      name: Summary
      path: templates/output/summary.md
tests:
  - name: Add Integers
    path: tests/integers
  - name: Add Floats
    path: tests/floats
script:
  uri: git@github.com:crosscompute/crosscompute-examples
  folder: add-numbers
  command: bash run.sh
environment: 
  image: docker.io/library/python:slim-buster
  processor: cpu
  memory: tiny
