---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
  - repo: local
    hooks:
      - id: clean-notebooks
        name: clean-notebooks
        entry: find . -name "*.ipynb" -prune -exec jupyter nbconvert --clear-output --inplace '{}' ';'
        language: system
        types: [jupyter]
        pass_filenames: false
