INPUT_FOLDER=$CROSSCOMPUTE_INPUT_FOLDER
OUTPUT_FOLDER=$CROSSCOMPUTE_OUTPUT_FOLDER
md-to-pdf --stylesheet $INPUT_FOLDER/style.css $INPUT_FOLDER/document.md
mv $INPUT_FOLDER/document.pdf $OUTPUT_FOLDER
