---
protocol: 0.8.3
name: Convert Timestamps
version:
  name: 0.1.0
input:
  variables:
    - id: timestamps
      name: Timestamps
      view: table
      path: timestamps.csv
    - id: timestamp-column
      name: Timestamp Column
      view: text
      path: settings.json
    - id: source-timezone
      name: Source Timezone
      view: text
      path: settings.json
    - id: target-timezone
      name: Target Timezone
      view: text
      path: settings.json
    - id: target-strftime
      name: Target Strftime
      view: text
      path: settings.json
  templates:
output:
  variables:
    - id: converted-timestamps
      name: Converted Timestamps
      view: table
      path: converted-timestamps.csv
  templates:
tests:
script:
  uri: git@github.com:crosscompute/crosscompute-examples
  folder: convert-timestamps
  command: bash run.sh
environment:
  image: docker.io/library/python:slim-buster
  processor: cpu
  memory: tiny
