---
protocol: 0.8.3
name: Count Words
version:
  name: 0.1.0
input:
  variables:
    - id: text
      name: text
      view: text
      path: t.txt
  templates:
    - id: input
      name: Input
      path: input.md
output:
  variables:
    - id: word-count 
      name: Word Count
      view: number
      path: word-count.json
    - id: word-counts
      name: Word Counts
      view: table
      path: word-count.csv
  templates:
    - id: output
      name: Output
      path: output.md
tests:
script:
  uri: git@github.com:crosscompute/crosscompute-examples
  folder: count-words
  command: bash run.sh
environment: 
  image: docker.io/library/python:slim-buster
  processor: cpu
  memory: tiny
