---
protocol: 0.8.3
name: Count Words
version:
  name: 0.1.0
input:
  variables:
    - id: text
      name: text
      view: string
      path: t.txt
  templates:
    - id: basic
      name: Basic
      path: templates/input/basic.md
output:
  variables:
    - id: word-count 
      name: Word Count
      view: number
      path: word-count.json
    - id: word-counts
      name: Word Counts
      view: table
      path: word-count.csv
  templates:
    - id: summary
      name: Summary
      path: templates/output/summary.md
tests:
script:
  uri: git@github.com:crosscompute/crosscompute-examples
  folder: count-words
  command: bash run.sh
environment: 
  image: docker.io/library/python:slim-buster
  processor: cpu
  memory: tiny
