---
protocol: 0.8.3
name: Transform Coordinates
version:
  name: 0.1.0
input:
  variables:
    - id: coordinates
      name: Coordinates
      view: table
      path: coordinates.csv
    - id: column-x
      name: Column X
      view: text
      path: settings.json
    - id: column-y
      name: Column Y
      view: text
      path: settings.json
    - id: source-proj4
      name: Source Proj4
      view: text
      path: settings.json
    - id: target-proj4
      name: Target Proj4
      view: text
      path: settings.json
  templates:
output:
  variables:
    - id: converted-coordinates
      name: Converted Coordinates
      view: table
      path: converted-coordinates.json
  templates:
tests:
script:
  uri: git@github.com:crosscompute/crosscompute-examples
  folder: transform-coordinates
  command: bash run.sh
environment: 
  image: osgeo/gdal
  processor: cpu
  memory: tiny
